export const LOGIN_REQUEST_START = 'LOGIN_REQUEST_START'
export const LOGIN_SUCCESS='LOGIN_SUCCES';
export const FAIL_TO_LOGIN ='FAIL_TO_LOGIN';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const FAIL_TO_REGISTER ='FAIL_TO_REGISTER'; 
export const REGISTER_REQUEST_START = 'REGISTER_REQUEST_START'

export const UPDATE_PROFILE_REQUEST_START = 'UPDATE_PROFILE_REQUEST_START'
export const UPDATE_PROFILE_SUCCESS='UPDATE_PROFILE_SUCCES';
export const FAIL_TO_UPDATE_PROFILE = 'FAIL_TO_UPDATE_PROFILE';

export const GET_PROFILE_REQUEST_START = 'GET_PROFILE_REQUEST_START'
export const GET_PROFILE_SUCCESS='GET_PROFILE_SUCCESS';
export const FAIL_TO_GET_PROFILE ='FAIL_TO_GET_PROFILE';




export const LOGOUT = 'LOGOUT';