export const ADD_ITEM_TO_CART= "ADD_ITEM_TO_CART"
export const REMOVE_ITEM_FROM_CART ="REMOVE_ITEM_FROM_CART"
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY"; 

export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS';
export const SAVR_PAYMENT_METHOD = 'SAVR_PAYMENT_METHOD'