export const GET_PRODUCTS = 'GET_PRODUCTS';
export const START_FETCHING = 'START_FETCHING';
export const FINISH_FETCHING = 'FINISH_FETCHING';
export const GET_PRODUCT = 'GET_PRODUCT';
export const FAIL_TO_FETCH_PRODUCTS = 'FAIL_TO_FETCH_PRODUCTS'
export const FETCHING_PRODUCTS_SUCCESS = 'FETCHING_PRODUCTS_SUCCESS';