export const START_FETCHING = 'START_FETCHING';
export const FINISH_FETCHING = 'FINISH_FETCHING';
export const FAIL_TO_FETCH_PRODUCTS = 'FAIL_TO_FETCH_PRODUCTS'
export const FAIL_TO_FETCH_PRODUCT = 'FAIL_TO_FETCH_PRODUCT'
export const FETCHING_PRODUCTS_SUCCESS = 'FETCHING_PRODUCTS_SUCCESS';
export const FETCHING_PRODUCT_SUCCESS = 'FETCHING_PRODUCT_SUCCESS';